apiVersion: v2
name: opentelemetry-demo-lite
type: application
version: 1.0.1
icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
description: A helm chart for openTelemetry community demo application integration with other component(lite version).
sources:
  - https://github.com/openinsight-proj/openinsight-helm-charts
maintainers:
  - name: JaredTan95
  - name: Frapschen
appVersion: "v1.4.0-beta-daocloud"
keywords:
  - opentelemetry
  - webstore-demo
dependencies:
  - name: opentelemetry-demo
    version: 0.21.1
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    condition: opentelemetry-demo.enabled