apiVersion: v2
name: opentelemetry-demo
type: application
version: 0.4.1
description: A helm chart for openTelemetry community demo application integration with other component.
sources:
  - https://github.com/openinsight-proj/openinsight-helm-charts
maintainers:
  - name: JaredTan95
  - name: Frapschen
appVersion: "0.4.1"
dependencies:
  - name: opentelemetry-demo
    version: 0.12.2
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    condition: opentelemetry-demo.enabled
