global:
  image:
    pullPolicy: IfNotPresent
  autoInstrumentation:
    enabled: true
    config:
      apiVersion: opentelemetry.io/v1alpha1
      kind: Instrumentation
      metadata:
        name: opentelemetry-autoinstrumentation-webstore-demo
        namespace: webstore-demo
      spec:
        # https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#instrumentationspecresource
        resource:
          addK8sUIDAttributes: true
        env:
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://insight-agent-opentelemetry-collector.insight-system.svc.cluster.local:4317
        sampler:
          # Enum: always_on, always_off, traceidratio, parentbased_always_on, parentbased_always_off, parentbased_traceidratio, jaeger_remote, xray
          type: always_on
        java:
          image: ghcr.m.daocloud.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.17.0
          env:
            - name: OTEL_JAVAAGENT_DEBUG
              value: "false"
            - name: OTEL_INSTRUMENTATION_JDBC_ENABLED
              value: "true"
            - name: SPLUNK_PROFILER_ENABLED
              value: "false"
        nodejs:
          image: ghcr.m.daocloud.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.31.0
        python:
          image: ghcr.m.daocloud.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python::0.33b0


opentelemetry-demo:
  enabled: true
  observability:
    otelcol:
      enabled: false
    jaeger:
      enabled: false

  default:
    enabled: false

  image:
    repository: m.daocloud.io/ghcr.io/open-telemetry/demo

  components:
    redis:
      enabled: true
      image: docker.m.daocloud.io/redis:alpine

    adService:
      enabled: true
      image: ghcr.m.daocloud.io/openinsight-proj/opentelemetry-demo-helm-chart/adservice:main
      servicePort: 9555
      ports:
        - name: http
          value: 8081
        - name: health-http
          value: 8999
      podAnnotations:
        instrumentation.opentelemetry.io/inject-sdk: 'true'
        sidecar.opentelemetry.io/inject: 'false'

    cartService:
      enabled: true
      podAnnotations:
        instrumentation.opentelemetry.io/inject-sdk: 'true'
        sidecar.opentelemetry.io/inject: 'false'

    checkoutService:
      enabled: true
      podAnnotations:
        instrumentation.opentelemetry.io/inject-sdk: 'true'
        sidecar.opentelemetry.io/inject: 'false'

    currencyService:
      enabled: true
      podAnnotations:
        instrumentation.opentelemetry.io/inject-sdk: 'true'
        sidecar.opentelemetry.io/inject: 'false'

    emailService:
      enabled: true
      podAnnotations:
        instrumentation.opentelemetry.io/inject-sdk: 'true'
        sidecar.opentelemetry.io/inject: 'false'

    featureflagService:
      enabled: true
      podAnnotations:
        instrumentation.opentelemetry.io/inject-sdk: 'true'
        sidecar.opentelemetry.io/inject: 'false'

    ffsPostgres:
      enabled: true

    frontend:
      enabled: true
      podAnnotations:
        instrumentation.opentelemetry.io/inject-sdk: 'true'
        sidecar.opentelemetry.io/inject: 'false'

    loadgenerator:
      enabled: true
      podAnnotations:
        instrumentation.opentelemetry.io/inject-sdk: 'true'
        sidecar.opentelemetry.io/inject: 'false'

    paymentService:
      enabled: true
      podAnnotations:
        instrumentation.opentelemetry.io/inject-sdk: 'true'
        sidecar.opentelemetry.io/inject: 'false'

    productCatalogService:
      enabled: true
      podAnnotations:
        instrumentation.opentelemetry.io/inject-sdk: 'true'
        sidecar.opentelemetry.io/inject: 'false'

    recommendationService:
      enabled: true
      podAnnotations:
        instrumentation.opentelemetry.io/inject-sdk: 'true'
        sidecar.opentelemetry.io/inject: 'false'


    shippingService:
      enabled: true
      podAnnotations:
        instrumentation.opentelemetry.io/inject-sdk: 'true'
        sidecar.opentelemetry.io/inject: 'false'

nacos:
  enabled: false
  version: 2.1.0
  replicaCount: 1
  image:
    repository: docker.m.daocloud.io/nacos/nacos-server
    tag: "v2.1.0-slim"
  nameOverride: "nacos-server"
  fullnameOverride: "nacos-server"
  service:
    type: NodePort
    port: 8848
    grpcPort1: 9848
    grpcPort2: 9849
  env:
    mode: standalone
    jvmXms: 1g
    jvmXmx: 1g
    jvmXmn: 512m
  resources:
    limits:
      cpu: 1024m
      memory: 1024Mi
    requests:
      cpu: 1024m
      memory: 1024Mi

sentinel:
  enabled: false
  version: 1.8.4
  replicaCount:
  image:
    repository: ghcr.m.daocloud.io/openinsight-proj/opentelemetry-demo-helm-chart/sentinel
    tag: "1.8.4"
  nameOverride: "sentinel-server"
  fullnameOverride: "sentinel-server"
  service:
    type: NodePort
    port: 34001
  env:
    javaopts: "-Dserver.port=34001 -Dcsp.sentinel.dashboard.server=0.0.0.0:34001 -Dproject.name=sentinel-dashboard"
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 200Mi
