global:
  image:
    pullPolicy: IfNotPresent
  autoInstrumentation:
    enabled: true
    config:
      apiVersion: opentelemetry.io/v1alpha1
      kind: Instrumentation
      metadata:
        name: opentelemetry-autoinstrumentation-webstore-demo
        namespace: webstore-demo
      spec:
        # https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#instrumentationspecresource
        resource:
          addK8sUIDAttributes: true
        env:
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://insight-agent-opentelemetry-collector.insight-system.svc.cluster.local:4317
        sampler:
          # Enum: always_on, always_off, traceidratio, parentbased_always_on, parentbased_always_off, parentbased_traceidratio, jaeger_remote, xray
          type: always_on
        java:
          image: ghcr.m.daocloud.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.17.0
          env:
            - name: OTEL_JAVAAGENT_DEBUG
              value: "false"
            - name: OTEL_INSTRUMENTATION_JDBC_ENABLED
              value: "true"
            - name: SPLUNK_PROFILER_ENABLED
              value: "false"
        nodejs:
          image: ghcr.m.daocloud.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.31.0
        python:
          image: ghcr.m.daocloud.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python::0.33b0


opentelemetry-demo:
  enabled: true
  observability:
    otelcol:
      enabled: false
    jaeger:
      enabled: false

  default:
    enabled: false

  image:
    repository: m.daocloud.io/ghcr.io/open-telemetry/demo

  components:
    redis:
      enabled: true
      image: docker.m.daocloud.io/redis:alpine

    adService:
      enabled: true
      image: ghcr.m.daocloud.io/openinsight-proj/opentelemetry-demo-helm-chart/adservice:v0.2.0
      servicePort: 9555
      ports:
        - name: http
          value: 8081
        - name: health-http
          value: 8999
      env:
        - name: AD_SERVICE_PORT
          value: '9555'
        - name: NACSO_NAMESPACE_ID
          value: ''
        - name: NACSO_GROUP_NAME
          value: DEFAULT_GROUP
        - name: SKOALA_REGISTRY
          value: nacos-test
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: >-
            k8s.namespace.name=$(K8S_NAMESPACE),k8s.node.name=$(OTEL_RESOURCE_ATTRIBUTES_NODE_NAME),k8s.pod.name=$(OTEL_RESOURCE_ATTRIBUTES_POD_NAME),k8s.pod.uid=$(OTEL_RESOURCE_ATTRIBUTES_POD_UID),skoala.registry=$(SKOALA_REGISTRY),nacos.namespaceid=$(NACSO_NAMESPACE_ID),nacos.groupname=$(NACSO_GROUP_NAME)
        - name: JAVA_OPTS
          value: -Dspring.cloud.nacos.config.server-addr=nacos-test.skoala-jia:8848 -Dspring.application.name=adservice-springcloud -Dspring.cloud.nacos.discovery.enabled=true -Dspring.cloud.nacos.discovery.server-addr=nacos-test.skoala-jia:8848 -Dspring.cloud.nacos.config.discovery.metadata.k8s_cluster_id=xxx -Dspring.cloud.nacos.config.discovery.metadata.k8s_cluster_name=skoala-dev -Dspring.cloud.nacos.config.discovery.metadata.k8s_namespace_name=skoala-jia -Dspring.cloud.nacos.config.discovery.metadata.k8s_workload_type=deployment -Dspring.cloud.nacos.config.discovery.metadata.k8s_workload_name=adservice-springcloud -Dspring.cloud.nacos.config.discovery.metadata.k8s_service_name=adservice-springcloud -Dspring.cloud.nacos.config.discovery.metadata.k8s_pod_name=$(HOSTNAME) -Dspring.cloud.sentinel.enabled=true -Dspring.cloud.sentinel.transport.dashboard=nacos-test-sentinel:8080

      podAnnotations:
        instrumentation.opentelemetry.io/inject-sdk: 'true'
        sidecar.opentelemetry.io/inject: 'false'

    cartService:
      enabled: true
      podAnnotations:
        instrumentation.opentelemetry.io/inject-sdk: 'true'
        sidecar.opentelemetry.io/inject: 'false'

    checkoutService:
      enabled: true
      podAnnotations:
        instrumentation.opentelemetry.io/inject-sdk: 'true'
        sidecar.opentelemetry.io/inject: 'false'

    currencyService:
      enabled: true
      podAnnotations:
        instrumentation.opentelemetry.io/inject-sdk: 'true'
        sidecar.opentelemetry.io/inject: 'false'

    emailService:
      enabled: true
      podAnnotations:
        instrumentation.opentelemetry.io/inject-sdk: 'true'
        sidecar.opentelemetry.io/inject: 'false'

    featureflagService:
      enabled: true
      podAnnotations:
        instrumentation.opentelemetry.io/inject-sdk: 'true'
        sidecar.opentelemetry.io/inject: 'false'

    ffsPostgres:
      enabled: true

    frontend:
      enabled: true
      podAnnotations:
        instrumentation.opentelemetry.io/inject-sdk: 'true'
        sidecar.opentelemetry.io/inject: 'false'

    loadgenerator:
      enabled: true
      podAnnotations:
        instrumentation.opentelemetry.io/inject-sdk: 'true'
        sidecar.opentelemetry.io/inject: 'false'

    paymentService:
      enabled: true
      podAnnotations:
        instrumentation.opentelemetry.io/inject-sdk: 'true'
        sidecar.opentelemetry.io/inject: 'false'

    productCatalogService:
      enabled: true
      podAnnotations:
        instrumentation.opentelemetry.io/inject-sdk: 'true'
        sidecar.opentelemetry.io/inject: 'false'

    recommendationService:
      enabled: true
      podAnnotations:
        instrumentation.opentelemetry.io/inject-sdk: 'true'
        sidecar.opentelemetry.io/inject: 'false'

    shippingService:
      enabled: true
      podAnnotations:
        instrumentation.opentelemetry.io/inject-sdk: 'true'
        sidecar.opentelemetry.io/inject: 'false'
