name: Setup
description: sets up helm lint and testing environment
inputs:
  create-kind-cluster:  # id of input
    description: 'Whether or not to create a kind cluster during setup'
    required: true
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v3.4
      with:
        version: v3.9.0

    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.3.0

    - name: Create kind cluster
      uses: helm/kind-action@v1.4.0
      if: ${{ inputs.create-kind-cluster == 'true' }}

    - name: Add Dependencies
      shell: bash
      run: |
          helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
          helm repo add bitnami https://charts.bitnami.com/bitnami 
          helm repo add redis https://ot-container-kit.github.io/helm-charts
          helm dep up charts/openinsight
          helm dep up charts/opentelemetry-demo
          helm dep up charts/opentelemetry-demo-lite