apiVersion: v1
kind: Service
metadata:
  name: otel-demo-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: otel-demo-ui
spec:
  type: NodePort
  ports:
    - name: service
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/component: frontend
    {{- include "otel-demo-ui.selectorLabels" . | nindent 4 }}
