global:
  image:
    pullPolicy: IfNotPresent
  env: &globalEnv
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://insight-agent-opentelemetry-collector.insight-system.svc.cluster.local:4317
    - name: OTEL_SERVICE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: 'metadata.labels[''app'']'
    - name: OTEL_K8S_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: OTEL_RESOURCE_ATTRIBUTES_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: OTEL_RESOURCE_ATTRIBUTES_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: k8s.namespace.name=$(OTEL_K8S_NAMESPACE),k8s.node.name=$(OTEL_RESOURCE_ATTRIBUTES_NODE_NAME),k8s.pod.name=$(OTEL_RESOURCE_ATTRIBUTES_POD_NAME)

opentelemetry-demo:
  enabled: true
  observability:
    otelcol:
      enabled: false
    jaeger:
      enabled: false

  image:
    repository: otel/demo
    pullSecrets: [ ]

  serviceAccount: ""

  components:
    redis:
      enabled: true
      image: redis:alpine
      ports:
        - name: redis
          value: 6379
    # overwrite
    adService:
      enabled: true
      image: ghcr.io/openinsight-proj/opentelemetry-demo-helm-chart/adservice:main
      ports:
        - name: service
          value: 9555
        - name: http
          value: 8081
      env:
        <<: *globalEnv
        - name: NACOS_SERVER
          value: nacos-server.opentelemetry-demo.svc.cluster.local:8848
        - name: SENTINEL_SERVER
          value: sentinel-server.opentelemetry-demo.svc.cluster.local:34001
        - name: JAVAOPTS
          value: -Dspring.cloud.nacos.discovery.enabled=true -Dspring.cloud.sentinel.enabled=true
    cartService:
      enabled: true
      servicePort: 8080
      env:
        <<: *globalEnv
        - name: ASPNETCORE_URLS
          value: http://*:8080

    checkoutService:
      enabled: true
      servicePort: 8080
      env:
        <<: *globalEnv

    currencyService:
      enabled: true
      servicePort: 8080
      env:
        <<: *globalEnv
        - name: PORT
          value: '8080'

    emailService:
      enabled: true
      servicePort: 8080
      env:
        <<: *globalEnv
        - name: APP_ENV
          value: production
        - name: PORT
          value: '8080'

    featureflagService:
      enabled: true
      env:
        <<: *globalEnv
        - name: DATABASE_URL
          value: ecto://ffs:ffs@ffs-postgres:5432/ffs
        - name: GRPC_PORT
          value: '50053'
        - name: PORT
          value: '50052'
      ports:
        - name: grpc
          value: 50052
        - name: http
          value: 50053

    ffsPostgres:
      enabled: true
      env:
        - name: POSTGRES_DB
          value: ffs
        - name: POSTGRES_PASSWORD
          value: ffs
        - name: POSTGRES_USER
          value: ffs
      image: cimg/postgres:14.2
      ports:
        - name: postgres
          value: 5432

    frontend:
      enabled: true
      servicePort: 8080
      env:
        <<: *globalEnv
        - name: FRONTEND_ADDR
          value: :8080

    loadgenerator:
      enabled: true
      env:
        <<: *globalEnv
        - name: USERS
          value: '10'
        - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
          value: python

    paymentService:
      enabled: true
      servicePort: 8080
      env:
        <<: *globalEnv

    productCatalogService:
      enabled: true
      servicePort: 8080
      env:
        <<: *globalEnv

    recommendationService:
      enabled: true
      servicePort: 8080
      env:
        <<: *globalEnv
        - name: OTEL_PYTHON_LOG_CORRELATION
          value: 'true'

    shippingService:
      enabled: true
      servicePort: 8080
      env:
        <<: *globalEnv
        - name: PORT
          value: '8080'

nacos:
  enabled: true
  version: 2.1.0
  replicaCount: 1
  image:
    repository: nacos/nacos-server
    tag: "v2.1.0-slim"
  nameOverride: "nacos-server"
  fullnameOverride: "nacos-server"
  service:
    type: NodePort
    httpNodePort: 30903
    grpcNodePort1: 30914
    grpcNodePort2: 30915
    port: 8848
    grpcPort1: 9848
    grpcPort2: 9849
  env:
    mode: standalone
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 200Mi

sentinel:
  enabled: true
  version: 1.8.4
  replicaCount: 1
  image:
    repository: ghcr.io/openinsight-proj/opentelemetry-demo-helm-chart/sentinel
    tag: "1.8.4"
  nameOverride: "sentinel-server"
  fullnameOverride: "sentinel-server"
  service:
    type: NodePort
    httpNodePort: 30924
    port: 34001
  env:
    javaopts: "-Dserver.port=34001 -Dcsp.sentinel.dashboard.server=0.0.0.0:34001 -Dproject.name=sentinel-dashboard"
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 200Mi

