{{- if not .Values.redis_resource.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    opentelemetry.io/name: {{ .Release.Name }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: {{ .Release.Name }}-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      name: redis
      targetPort: 6379
  selector:
    opentelemetry.io/name: {{ .Release.Name }}-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    opentelemetry.io/name: {{ .Release.Name }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: {{ .Release.Name }}-redis
spec:
  selector:
    matchLabels:
      opentelemetry.io/name: {{ .Release.Name }}-redis
  template:
    metadata:
      labels:
        opentelemetry.io/name: {{ .Release.Name }}-redis
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: redis
        app.kubernetes.io/name: {{ .Release.Name }}-redis
    spec:
      containers:
        - name: redis
          image: 'docker.m.daocloud.io/redis:alpine'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name: redis
          resources:
            limits:
              memory: 20Mi
          securityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 999
{{- end }}
