{{- if .Values.global.serviceMonitor.otelcol.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    operator.insight.io/managed-by: insight
  name: otelcol-monitor
spec:
  endpoints:
    - honorLabels: true
      port: prometheus
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: otelcol
{{- end }}

