name: Lint Charts (Demo)

on:
  pull_request:
    paths:
      - 'charts/opentelemetry-demo/**'
    branches:
      - main
env:
  CT_CHART_DIRS: charts/opentelemetry-demo

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
        with:
          create-kind-cluster: "false"

      - name: Run chart-testing (lint)
        run: ct lint --target-branch main
