name: Release Charts

on:
  push:
    branches:
      - main
    tags: ["v*"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3.1
        with:
          version: v3.4.1

      - name: Add dependent repositories
        run: |
          helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
          helm repo add bitnami https://charts.bitnami.com/bitnami    
          helm repo add redis https://ot-container-kit.github.io/helm-charts
          helm dep up charts/openinsight
          helm dep up charts/opentelemetry-demo

      - name: Add DaoCloud Registry
        env:
          DAOCLOUD_COMMUNITY_REGISTRY_URL: release.daocloud.io
          DAOCLOUD_COMMUNITY_REGISTRY_USERNAME: ${{ secrets.DAOCLOUD_REGISTRY_USERNAME }}
          DAOCLOUD_COMMUNITY_REGISTRY_PASSWORD: ${{ secrets.DAOCLOUD_REGISTRY_PASSWORD }}
        run: |
          helm registry login $DAOCLOUD_COMMUNITY_REGISTRY_URL --username $DAOCLOUD_COMMUNITY_REGISTRY_USERNAME --password $DAOCLOUD_COMMUNITY_REGISTRY_PASSWORD

      - name: Release Helm chart to DaoCloud Community Chart Repo
        uses: helm/chart-releaser-action@v2
        env:
          CR_TOKEN: "${{ secrets.ACTIONS_TOKEN }}"
        with:
          chart: opentelemetry-demo
          charts_repo: chartrepo/community
          extra_args: "--destination $DAOCLOUD_COMMUNITY_REGISTRY_URL"

