name: Test Chart

on:
  pull_request:
    paths:
      - 'charts/opentelemetry-demo/**'
      - 'charts/openinsight/**'
    branches:
      - main

jobs:
  demo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.9.2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

#      - name: Create kind cluster
#        uses: helm/kind-action@v1.2.0
#        if: steps.list-changed.outputs.changed == 'true'
#
#      - name: sync dependency
#        run: helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
#
#      - name: Run chart-testing (install)
#        run: ct install --target-branch ${{ github.event.repository.default_branch }}