{{- if .Values.extensions.springCloudGateway.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel-demo.name" . }}-spring-cloud-gateway
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: spring-cloud-gateway
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ .Release.Name }}-spring-cloud-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/component: spring-cloud-gateway
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Release.Name }}-spring-cloud-gateway
    spec:
      containers:
          - name: spring-cloud-gateway
            image: "{{ .Values.extensions.springCloudGateway.image.repository }}:{{ .Values.extensions.springCloudGateway.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: Always
            ports:
              - name: http
                containerPort: 18080
                protocol: TCP
            env:
              - name: ADSERVICE_ADDR
                value: 'http://{{ include "otel-demo.name" . }}-adservice:8081'
              - name: AUTH_ENABLED
                value: "false"
            resources:
              limits:
                memory: 512Mi

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-demo.name" . }}-spring-cloud-gateway
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.extensions.springCloudGateway.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: 18081
      protocol: TCP
      targetPort: 18081
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-spring-cloud-gateway
  {{- end }}